volumes:
  pgdata:
  static:

services:

  nginx:
    image: nginx:1.29
    container_name: nginx
    restart: unless-stopped
    ports:
      - '8000:80'
    volumes:
      - static:/var/html/static/
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf
  

  postgres:
    image: postgres:18.1-alpine
    container_name: db
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file:
      - ./.env-prod
  

  web:
    image: sergeiban/pathfinder_web:latest
    container_name: backend
    restart: unless-stopped
    volumes:
      - static:/app/static_production/
    env_file: .env-prod
    depends_on:
      - postgres
      - nginx